#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
CLEAR='\033[0m'

#EYE_BIN='/usr/local/bin/eye'
#RUN_USER='deploy'

eye_log() {
  echo "`date`:$RUN_USER: $1 " >> $LOG_FILE
}

is_rvm() {
  if [ "$USER" = "$RUN_USER" ];
  then
    bash -l -c "type rvm | cat | grep -q '^rvm is a function$'" > /dev/null 2>&1
  else
    su $RUN_USER -l -c "type rvm | cat | head -1 | grep -q '^rvm is a function$'" > /dev/null 2>&1
  fi
}

run_as() {
  if [ "$USER" = "$RUN_USER" ]; then
    bash -l -c "$1"
  else
    su $RUN_USER -l -c "$1"
  fi
}

execute() {
  if is_rvm;
  then
    CMD="rvm system do ${EYE_BIN} $@"
  else
    CMD="${EYE_BIN} $@"
  fi
  run_as "$CMD"
}

status() {
   echo -e "Info:\n"
   execute info $1
   if [ $2 ]; then
      echo -e "Xinfo:\n"
      execute xinfo
      echo -e "Config:\n"
      execute xinfo -c
   fi
}

start() {
  execute load
}

stop() {
   local opts=''
   if [ $1 ]; then
    opts='--stop-all'
   fi
   execute quit ${opts}
}

check() {
  execute check $1
}

explain() {
  execute explain $1
}

expand_path() {
  realpath "${CONFIG_DIR}/$1"
}

check_all() {
  local check=0
  local explain=$1
  local trace=$2
  local config_file
  local output
  for config_file in `ls -1 $CONFIG_DIR`
  do
    if ! check_file $(expand_path ${config_file}) ${explain} ${trace}; then
      check=0
    fi
  done
  return ${check}
}

check_file() {
  local config_file=$1
  local explain=$2
  local trace=$3
  local output
  if [ ! -z $explain ];then
    output=$(explain ${config_file})
  else
    output=$(check ${config_file})
  fi

  if [ "$?" -eq "0" ]; then
    echo -e "Check ${config_file} [ ${GREEN}OK${CLEAR} ]"
    if [ "$trace" = true ] && [ "$explain" = true ]; then
      echo -e $output
    fi
    return 0
  else
    echo -e "Check ${config_file} [ ${RED}FAIL${CLEAR} ]"
    if [ "$trace" = true ]; then
      echo -e "$output"
    fi
    return 1
  fi
}

load_file() {
  local config_file=$1
  local output=$(execute load ${config_file} 2>&1)
  if [ "$?" -eq "0" ];
  then
      echo -e "Load ${config_file} [ ${GREEN}OK${CLEAR} ]"
  else
      eye_log "$output"
      echo -e "Load ${config_file} [ ${RED}FAIL${CLEAR} ]"
  fi
}

reload_all() {
  if check_all;  then
    local config_file
    local config_count
    eye_log $(execute delete all 2>&1)
    config_count=$(ls -1 ${CONFIG_DIR} | wc -l);
    if [ ${config_count} \> 0 ]; then
       for config_file in `ls -1 ${CONFIG_DIR}`
       do
         load_file $(expand_path ${config_file})
       done
    fi
  fi
}
